# Generated by Django 6.0 on 2026-01-07 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_demo_url_project_github_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='github_url',
        ),
    ]
