# Generated by Django 6.0 on 2026-01-07 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_project_github_url'),
        ('users', '0002_studentprofile_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='student_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.studentprofile'),
        ),
    ]
